services:
  api:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - type: bind
        source: ./df_hourly.csv
        target: /app/df_hourly.csv
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ./artifacts
        target: /app/artifacts
        read_only: true
        bind:
          create_host_path: false
    restart: unless-stopped
